# Generated by Django 5.2.5 on 2025-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carouselslider_cart_countrymultiplier_discountcode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='CountryMultiplier',
            new_name='CountriesMultiplier',
        ),
        migrations.RenameModel(
            old_name='GoldCategory',
            new_name='GoldCategories',
        ),
        migrations.RenameModel(
            old_name='GoldSubCategory',
            new_name='GoldSubCategories',
        ),
        migrations.RenameModel(
            old_name='ImitationCategory',
            new_name='ImitationCategories',
        ),
        migrations.RenameModel(
            old_name='ImitationSubCategory',
            new_name='ImitationSubCategories',
        ),
        migrations.RenameModel(
            old_name='SilverCategory',
            new_name='SilverCategories',
        ),
        migrations.RenameModel(
            old_name='SilverSubCategory',
            new_name='SilverSubCategories',
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='button_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='button_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='subtitle_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='title_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
