# Generated by Django 5.2.5 on 2025-09-11 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Imitation', 'Imitation')], default='Gold', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='India', max_length=100, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CountriesMultiplier',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.AddField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.user'),
        ),
        migrations.AddField(
            model_name='goldcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gold_categories/'),
        ),
        migrations.AddField(
            model_name='goldcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldcategories',
            name='name',
            field=models.CharField(default='Unnamed Gold Category', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='carat_metal_purity',
            field=models.CharField(default='24k', max_length=10),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gold_products', to='app.goldcategories'),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gold_products/'),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gold_products/'),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='gold_products/'),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='name',
            field=models.CharField(default='Unnamed Gold Product', max_length=200),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gold_products', to='app.goldsubcategories'),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gold_products/videos/'),
        ),
        migrations.AddField(
            model_name='goldproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goldsubcategories',
            name='gold_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.goldcategories'),
        ),
        migrations.AddField(
            model_name='goldsubcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gold_subcategories/'),
        ),
        migrations.AddField(
            model_name='goldsubcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldsubcategories',
            name='name',
            field=models.CharField(default='Unnamed Gold SubCategory', max_length=100),
        ),
        migrations.AddField(
            model_name='imitationcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imitation_categories/'),
        ),
        migrations.AddField(
            model_name='imitationcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imitationcategories',
            name='name',
            field=models.CharField(default='Unnamed Imitation Category', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imitation_products', to='app.imitationcategories'),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='imitation_products/'),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='imitation_products/'),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='imitation_products/'),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='material_details',
            field=models.CharField(default='Brass', max_length=100),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='name',
            field=models.CharField(default='Unnamed Imitation Product', max_length=200),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imitation_products', to='app.imitationsubcategories'),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='imitation_products/videos/'),
        ),
        migrations.AddField(
            model_name='imitationproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='imitationsubcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imitation_subcategories/'),
        ),
        migrations.AddField(
            model_name='imitationsubcategories',
            name='imitation_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.imitationcategories'),
        ),
        migrations.AddField(
            model_name='imitationsubcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imitationsubcategories',
            name='name',
            field=models.CharField(default='Unnamed Imitation SubCategory', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('NetBanking', 'NetBanking'), ('Cash', 'Cash')], default='UPI', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='heading',
            field=models.CharField(default='Review Heading', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.user'),
        ),
        migrations.AddField(
            model_name='silvercategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='silver_categories/'),
        ),
        migrations.AddField(
            model_name='silvercategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='silvercategories',
            name='name',
            field=models.CharField(default='Unnamed Silver Category', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='silver_products', to='app.silvercategories'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='silver_products/'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='silver_products/'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='silver_products/'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='name',
            field=models.CharField(default='Unnamed Silver Product', max_length=200),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='purity',
            field=models.CharField(default='Sterling 92.5', max_length=50),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='silver_products', to='app.silversubcategories'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='silver_products/videos/'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='silversubcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='silver_subcategories/'),
        ),
        migrations.AddField(
            model_name='silversubcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='silversubcategories',
            name='name',
            field=models.CharField(default='Unnamed Silver SubCategory', max_length=100),
        ),
        migrations.AddField(
            model_name='silversubcategories',
            name='silver_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.silvercategories'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='app.user'),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='button_link',
            field=models.URLField(blank=True, default='https://example.com', null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='button_name',
            field=models.CharField(blank=True, default='Click Here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='subtitle',
            field=models.CharField(blank=True, default='Carousel Subtitle', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='title',
            field=models.CharField(blank=True, default='Carousel Title', max_length=200, null=True),
        ),
    ]
