# Generated by Django 5.2.5 on 2025-09-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_countrymultiplier_delete_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Gold Category', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gold_category/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImitationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Imitation Category', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imitation_category/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SilverCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Silver Category', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='silver_category/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='goldsubcategories',
            name='gold_category',
        ),
        migrations.RemoveField(
            model_name='imitationsubcategories',
            name='imitation_category',
        ),
        migrations.RemoveField(
            model_name='silversubcategories',
            name='silver_category',
        ),
        migrations.AlterField(
            model_name='goldproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gold_products', to='app.goldcategory'),
        ),
        migrations.CreateModel(
            name='GoldSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Gold SubCategory', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gold_subcategory/')),
                ('is_active', models.BooleanField(default=True)),
                ('gold_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='app.goldcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='goldproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gold_products', to='app.goldsubcategory'),
        ),
        migrations.AlterField(
            model_name='imitationproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imitation_products', to='app.imitationcategory'),
        ),
        migrations.CreateModel(
            name='ImitationSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Imitation SubCategory', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imitation_subcategory/')),
                ('is_active', models.BooleanField(default=True)),
                ('imitation_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='app.imitationcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='imitationproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imitation_products', to='app.imitationsubcategory'),
        ),
        migrations.AlterField(
            model_name='silverproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='silver_products', to='app.silvercategory'),
        ),
        migrations.CreateModel(
            name='SilverSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Silver SubCategory', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='silver_subcategory/')),
                ('is_active', models.BooleanField(default=True)),
                ('silver_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='app.silvercategory')),
            ],
        ),
        migrations.AlterField(
            model_name='silverproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='silver_products', to='app.silversubcategory'),
        ),
        migrations.DeleteModel(
            name='GoldCategories',
        ),
        migrations.DeleteModel(
            name='GoldSubCategories',
        ),
        migrations.DeleteModel(
            name='ImitationCategories',
        ),
        migrations.DeleteModel(
            name='ImitationSubCategories',
        ),
        migrations.DeleteModel(
            name='SilverCategories',
        ),
        migrations.DeleteModel(
            name='SilverSubCategories',
        ),
    ]
