# Generated by Django 5.2.5 on 2025-09-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_goldcategory_imitationcategory_silvercategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslider',
            options={'verbose_name': 'Carousel Slider', 'verbose_name_plural': 'Carousel Slider'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='countrymultiplier',
            options={'verbose_name': 'Country Multiplier', 'verbose_name_plural': 'Country Multiplier'},
        ),
        migrations.AlterModelOptions(
            name='goldcategory',
            options={'verbose_name': 'Gold Category', 'verbose_name_plural': 'Gold Category'},
        ),
        migrations.AlterModelOptions(
            name='goldproduct',
            options={'verbose_name': 'Gold Product', 'verbose_name_plural': 'Gold Product'},
        ),
        migrations.AlterModelOptions(
            name='goldsubcategory',
            options={'verbose_name': 'Gold SubCategory', 'verbose_name_plural': 'Gold SubCategory'},
        ),
        migrations.AlterModelOptions(
            name='imitationcategory',
            options={'verbose_name': 'Imitation Category', 'verbose_name_plural': 'Imitation Category'},
        ),
        migrations.AlterModelOptions(
            name='imitationproduct',
            options={'verbose_name': 'Imitation Product', 'verbose_name_plural': 'Imitation Product'},
        ),
        migrations.AlterModelOptions(
            name='imitationsubcategory',
            options={'verbose_name': 'Imitation SubCategory', 'verbose_name_plural': 'Imitation SubCategory'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='silvercategory',
            options={'verbose_name': 'Silver Category', 'verbose_name_plural': 'Silver Category'},
        ),
        migrations.AlterModelOptions(
            name='silverproduct',
            options={'verbose_name': 'Silver Product', 'verbose_name_plural': 'Silver Product'},
        ),
        migrations.AlterModelOptions(
            name='silversubcategory',
            options={'verbose_name': 'Silver SubCategory', 'verbose_name_plural': 'Silver SubCategory'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlist'},
        ),
    ]
