# Generated by Django 5.2.5 on 2025-09-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_carouselslider_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymultiplier',
            name='country_name',
            field=models.CharField(choices=[('India', 'India'), ('Others', 'Others')], default='India', max_length=100, unique=True),
        ),
    ]
