# Generated by Django 5.2.5 on 2025-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_countrymultiplier_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslider',
            name='button_color',
            field=models.CharField(blank=True, default='#000000', help_text='Choose button color', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='button_link',
            field=models.CharField(blank=True, default='/new-arrivals/', help_text='Enter URL path like /new-arrivals/ or /gold-collection/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='subtitle_color',
            field=models.CharField(blank=True, default='#000000', help_text='Choose subtitle color', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='title_color',
            field=models.CharField(blank=True, default='#000000', help_text='Choose title color', max_length=7, null=True),
        ),
    ]
