# Generated by Django 5.2.5 on 2025-09-13 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_carouselslider_button_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslider',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Carousel Slider', 'verbose_name_plural': 'Carousel Slider'},
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this slider active?'),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (0 = first)'),
        ),
        migrations.AddField(
            model_name='carouselslider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this product active and visible?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this product on homepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price for discount calculation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='button_color',
            field=models.CharField(blank=True, default='#2d5a3d', help_text='Choose button color', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='subtitle_color',
            field=models.CharField(blank=True, default='#4b5563', help_text='Choose subtitle color', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='title_color',
            field=models.CharField(blank=True, default='#2d5a3d', help_text='Choose title color', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_set', to='app.product'),
        ),
        migrations.CreateModel(
            name='EnhancedWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_wishlist_set', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enhanced Wishlist Item',
                'verbose_name_plural': 'Enhanced Wishlist Items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
