# Generated by Django 5.2.7 on 2025-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="confirm_password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
